spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Hotel-project
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  application:
    name: Hotel-project
  jpa:
    hibernate:
      ddl-auto: update